language: node_js
node_js:
  - "10"
  - "9"
  - "8"
install:
  - npm install
script: echo "Skipping tests for now"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
